name: Stage environment sync
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Merge main -> qa-beta
        uses: robotology/gh-action-nightly-merge@v1.3.3
        with:
          allow_ff: true
          ff_only: true
          stable_branch: main
          development_branch: qa-beta
          push_token: 'GITHUB_TOKEN'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Open pull request main -> qa-stable
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: main
          TO_BRANCH: qa-stable
